### ISSUE TITLE
RAP64 addition

### ISSUE THREAD

**Issue by salvadorc17** [RetroAchievements/RASuite#12]
Hi Scott, i do have the source for P64 working and be able to use with RA but i was not able to add the overlay, want me to push this emulator so you can complete and upload to site?

**Comment by RetroAchievements** [comment]
That sounds amazing! Yes please, i'll add you to the main RA project

**Comment by salvadorc17** [comment]
You have been able to compile latest version, because if not we can use older as base for emulator.
