### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by coczero** [RetroAchievements/RASuite#13]
I'd like to start documenting most of the RA_Integration code.
But I have no idea what documentation style to use in c++.
Can anyone give a small example on how we should document in this project?

**Comment by GameDragon2k** [comment]
Generally when I hear about code documentation tools, I hear about Doxygen. 

I haven't used it personally, so I'm not exactly sure if it's what you're looking for, but I'd check that out maybe.

**Comment by coczero** [comment]
Yea, Doxygen is what we use at work too. If everyone is alright with that documenting style, I would start documenting.

**Comment by GameDragon2k** [comment]
I'm all for it personally.

@RetroAchievements what do you think?

**Comment by RetroAchievements** [comment]
Anything that doesn't involve adding tons of multi-line comments with unintelligible prefixes all over every function. I'm all for making the code clearer, definitely, but please remember that this code is meant to work low level, with lots of existing apps, of all different types of implementations, which doesn't lend itself well to rigidity. I'm on hols at the mo, back on Friday, i haven't had good experiences with doxygen but if it's integrated seamlessly I'm sure it'll be fine :)

**Comment by coczero** [comment]
I agree that Doxygen might be a bit overkill as it is designed with creating an output file in mind, which we don't need. But I think it is important to have comments that are shown by intellisense while developing. And it should also show the comments of the return value and the parameters.

**Comment by coczero** [comment]
Maybe like the first answer here?
http://stackoverflow.com/questions/2198241/best-practice-for-c-function-commenting

I tried it and it works except for the return value comment.

**Comment by SyrianBallaS** [comment]
Use Doxygen with XML comments, you can look at my repo if you want to see how it looks https://github.com/SyrianBallaS/RASuite.

It was originally only for .NET but C++ can use it too.

**Comment by meleu** [comment]
@coczero after one year looks like the intention to do what was proposed in the OP is gone.

I'm closing this issue, but feel free to reopen if you think it's reasonable.
