### ISSUE TITLE
Extra system id and slots 

### ISSUE THREAD

**Issue by salvadorc17** [RetroAchievements/RASuite#19]
Hi @RetroAchievements (Scott) im working on new emulators that can be added to RA in short time, but i will need to have Integration compatibility for those, right now im working this way. 
RAAtari = 13,
RANeoGeo = 14

Would be cool to have those allowed in the site. example game here.
http://retroachievements.org/Game/9984

**Comment by RetroAchievements** [comment]
Yep, all done

**Comment by salvadorc17** [comment]
Thanks, still need to wait until you add those to RADefs.h and update integration for use it.
