### ISSUE TITLE
Compiling with scons

### ISSUE THREAD

**Issue by SyrianBallaS** [RetroAchievements/RASuite#2]
Hi Guys,

It seems I'm having trouble getting this to compile. I have all the dependencies needed that are listed in readme-sdl. Here's a screenshot of the error.

![image](https://cloud.githubusercontent.com/assets/18649925/15104718/561cc1cc-1589-11e6-9a58-e4498d7eda30.png)

**Comment by ImmenseGames** [comment]
Hey - what is scons? I'm only using Visual Studio to compile

**Comment by SyrianBallaS** [comment]
scons is kind of like cmake, I read it somewhere in RANes folder. 

I tried compiling with visual studio but there seems to be a lot of conflicts. I'm gonna guess the last time the master branch was compiled was before VS2015 came out. I get a lot of conflicts between macros and snprintf from stdio.h
