### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by leiradel** [RetroAchievements/RASuite#45]
Although one might infer that the RASuite code is licensed under the GPL, since it's both compiled into and dynamically linked to other GPL'ed projects, it's best to be clear about it.

As the RALibretro developer, I'd like to make sure under what terms I can use RA code.

**Comment by meleu** [comment]
@RetroAchievements @ScottFromDerby 
Just to remember RALibretro is a front-end to develop (and earn) achievements using the libretro cores for emulation. Development is happning here: https://github.com/leiradel/RASuite

According "[How to use GNU licenses for your own software](https://www.gnu.org/licenses/gpl-howto.en.html)" document, this is what would be needed to make all code on this repo GPL compliant:

- Give each file the proper copyright notices.
- Add a COPYING file with a copy of the GNU GPL or GNU AGPL.
- Put a license notice in each file.

If you think we can add a license notice in each source file of this repo I can take care of it and submit a PR. Just tell me what notice do you want to put.

**Comment by ScottFromDerby** [comment]
I *think* all emulators we've used are GPL, which I *think* means we don't have a choice in the matter, however is GPL still the best choice? https://opensource.com/article/17/2/decline-gpl I'm not up to date with licensing, I've not had chance to educate myself fully about it

**Comment by ScottFromDerby** [comment]
From my perspective, my official stance is "do what you like". Ctrl+A Ctrl+P and live under the printouts if you like

**Comment by leiradel** [comment]
Thanks for the answer @ScottFromDerby but like you said, I too believe there's no choice. Also, people are afraid of using code which doens't have a clear license, because having no explicit license doesn't mean it's not copyrighted and that the owner won't want to exercise their rights on the code.

**Comment by leiradel** [comment]
I take that back. Of course there are options, any GPL-compatible license can be used. If you want to release the source code under a "do what you like" license, I suggest releasing it under the [3-clause BSD](https://opensource.org/licenses/BSD-3-Clause), [MIT](https://opensource.org/licenses/MIT), or [zlib/libpng](https://opensource.org/licenses/Zlib), but don't take my word, look around and decide what's best for you and RASuite.

Other OSI-approved licenses can be found [here](https://opensource.org/licenses). A list of GPL-compatible licenses can be found [here](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses). Again, it's better to have a clear statement on how the code can be used otherwise people will be afraid of using it in their code.

**Comment by meleu** [comment]
@leiradel 
Can we close this issue?

**Comment by leiradel** [comment]
Better ask the integration developers. RALibretro is GPL, but it's still unclear what the integration license is.

**Comment by leiradel** [comment]
Let me put it in a different way: right now we're violating the license of the libretro cores that are GPL, because I compile code into RALibretro which doesn't have an explicit license stating that it can be used in GPL'ed code.

**Comment by meleu** [comment]
This issue was moved to RetroAchievements/RAIntegration#20
