### ISSUE TITLE
ResetIf HitCount

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RASuite#54]
As a developer, I'd like to create a ResetIf condition that only resets the achievement if it happens a certain number of times.

We already have several examples of "Defeat boss without taking damage", but it's impossible to do something like "Defeat boss without jumping more than three times". To do that, you'd need a counter on the ResetIf condition.

Just like regular conditions, when the ResetIf condition is true, it will increment the counter. When the counter reaches the target, then the achievement will be reset.

Because it's tied to a HitCount, any other ResetIf in the achievement may reset its HitCount, but that's desirable as the entire achievement is supposed to reset if any ResetIf is true.

Existing achievements should be audited. Anything with a ResetIf HitCount(1) will be compatible with the change as the counter will increment to 1 and immediate reset the achievement. Anything with a ResetIf HitCount(>1) will have to be modified. As the HitCount clause currently has no effect on the ResetIf conditions, they should be changed to HitCount(0).

**Comment by meleu** [comment]
This issue was moved to RetroAchievements/RAIntegration#1
