### ISSUE TITLE
PauseIf HitCount

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RASuite#55]
As a developer, I'd like to create a PauseIf condition that only pauses the achievement if it happens a certain number of times.

Just like regular conditions, when the PauseIf condition is true, it will increment the counter. When the counter reaches the target, then the condition group (core or alt) will be paused. When the condition is false, the counter _is not reset_. To reset the counter, a seperate ResetIf condition must be present.

This would allow for achievements like "Complete the level without jumping more than three times". Each jump would increment the counter. When it hits four, the achievement is disabled until the user restarts the level and a ResetIf resets the counter.

PauseIf HitCount could also be used as a makeshift timer. If you know the framerate of your system you can create an achievement like "Complete the level in under 30 seconds" that has a PauseIf level=X HitCount (30*frames).

Existing achievements should be audited. Anything with a PauseIf HitCount(1) will be compatible with the change as the counter will increment to 1 and immediately pause the condition group. Anything with a PauseIf HitCount(>1) will have to be modified. As the HitCount clause currently has no effect on the PauseIf conditions, they should be changed to HitCount(0).

**Comment by meleu** [comment]
This issue was moved to RetroAchievements/RAIntegration#2
