### ISSUE TITLE
Ability to manually reset an achievement

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RASuite#60]
As a developer, I'd like to explicitly reset all the HitCounts in an achievement to 0. Suggest adding a button to the achievement editor to do so.

**Comment by kdecks** [comment]
I've found a quick way to do this is deactivate and then reactivate the individual achievement. (This only works in local and unofficial)

**Comment by meleu** [comment]
This issue was moved to RetroAchievements/RAIntegration#7
