### ISSUE TITLE
Integrated leaderboard editor

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RASuite#63]
As a developer, I would like the ability to define a leaderboard using the toolkit. Currently I have to manually generate the expressions and load them into the web page, then restart the game to pull them from the webpage in order to try the leaderboard. As the leaderboard is fully active, submissions are made when the leaderboard submit condition is met. It would be preferable to be able to edit and test leaderboard locally before uploading them to the web page.

**Comment by meleu** [comment]
This issue was moved to RetroAchievements/RAIntegration#10
