### ISSUE TITLE
Permission validation in toolkit

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RASuite#64]
As a non-developer, I don't want the buttons for promoting achievements to be active as pushing them will only generate an error. Alternately, a permissions error could be displayed without sending anything to the server.

There is currently no way to determine the user's account type in the toolkit. Changes would have to be made to return it from one of the APIs (probably the login API).

There are other things that could be better handled in the toolkit knowing the user's account type, like ROM linking.

**Comment by meleu** [comment]
Maybe it's something to be sorted by @RetroAchievements/raweb

**Comment by GameDragon2k** [comment]
This would fix numerous issues so I'm all for this.

**Comment by ScottFromDerby** [comment]
Agreed, this would be great, I'm all for this. We'll need the server to
spit out permissions on login, and to store them in app secondarily

**Comment by kdecks** [comment]
Very useful.

**Comment by meleu** [comment]
This issue was moved to RetroAchievements/RAIntegration#11
