### ISSUE TITLE
RANes Lua Scripts not working

### ISSUE THREAD

**Issue by ismaelnovo** [RetroAchievements/RASuite#69]
I want to test the rewind script and is not working. In latest fceux is working perfecty if I drop the Lua file in the window. In the RA versión I can't start the script.

**Comment by meleu** [comment]
Hi @ismaelnovo 

We are moving the emulators code to another repo: https://github.com/RetroAchievements/RAEmus

If you still think that your report is an issue, please open it at that repo's issue tracker.

I'm closing this one.
