### ISSUE TITLE
HitCount for leaderboard value

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RASuite#70]
As a developer, I'd like to create a leaderboard whose value is a HitCount condition, not a memory address.

For example, Mario's coin counter resets at 100, so there's no way to create a leaderboard for most coins collected in a playthrough. I'd like the value to be `hitcount(coins != delta(coins))`

**Comment by Jamiras** [comment]
The value field currently uses a different syntax than the condition format, which would be incompatible. A prefix would have to switch modes:

Existing format looks like: `0xH1234*10_0xH1235_v1` where the memory address is the same syntax, but `*` is raw multiplication (not supported by conditions), and `_` means `add`, not `and`. Additionally, the `v` indicates a raw value and supports negative values, whereas conditions just have raw numbers without a size indicator.

Suggested format would be something like `H:0xH1234!=d0xH1234`. The "H:" prefix indicates it's a HitCount value, and the remaining portion of the string is the condition. In an achievement, this would be written `0xH1234!=d0xH1234.10.` where the `.10.` indicates the target HitCount. Since a leaderboard doesn't have a target, that part would be left off.

**Comment by meleu** [comment]
This issue was moved to RetroAchievements/RAIntegration#13
