### ISSUE TITLE
GUI Simplification Project and other refactorings

### ISSUE THREAD

**Issue by SyrianBallaS** [RetroAchievements/RASuite#77]
Putting this in here as a heads up, stuff will be done one at a time. Functionality/feature-wise nothing is intended to be different, but the code will be vastly transformed when this is done. If you have any questions or advice please come forward.

# GUI Simplification Project
## Libraries
_N.B.: The emulators will not depend on any of this stuff_
- [ ] RapidJSON v1.1.0
    - What to expect
       - `std::i/ofstream` will be used instead of `FILE*`
       - `rapidjson::I/OStreamWrapper` instead instead of `rapidjson::FileStream`.
       - DataStream will be a string instead of a vector; `using DataStream = std::basic_string<BYTE>; `
       - Many files will change
- [ ] tinyformat.h (3rd party)
    - Uses output streams in **printf syntax** which returns std::string
    - What to expect:
       - Every single `printf `like statement will be replaced with `tfm::format` including `RA_LOG`
- [ ] Precompiled Header
    - Makes the dll build in a few seconds if the pch was already built.

### Helpers and Improvements
- [ ] Replace COM interfaces with ATL smart pointers
    - Example: instead of `IFileDialog*` you'll see `CComPtr<IFileDialog>`, prevents leaks
- [ ] Safer string conversion, and other helper conversion functions
    - What to expect:
       - Many of these functions will templates, to be used with any valid type
           - There will be instant/compile time checks to prevent misuse, if it wasn't a valid type you will get an intellisense error.
       - Conversion will be done through a stream to ensure every character is converted correctly
       - Implementation of a few concepts, i.e., `EqualityComparable`, `LessThanComparable`, `Comparable`, also to check if something is a character or a string. (these can be used in a `static_assert`)
       - A very easy signed/unsigned conversion for any valid type, etc
       - An `enum `to `underlying_type `conversion function (needed if using `enum class)`
- [ ] Colors as named enums
    - This is prevent having to memorize the `RGB` code
- [ ] Lots of comparison operators
    - What to expect:
       - To ensure something is comparable they at least need an equality and less than operator, the rest 
          are handled by std::rel_ops
       - Since enum classes prevent implicit conversion to int they need operators (an example would be ` std::byte`, it's an enum class with an `underlying_type `of` unsigned char `)
- [ ] Replace all constant global C arrays with `std::array`
- [ ] Replace macros with `constexpr` variables and/or function templates where possible

## Generic Interfaces
Basically these two will work with any Window (if top-level) or dialog (RA Dialogs aren't top-level). The window class is the initial registration point for window/dialog/control/etc.
- [ ] Base dialog
- [ ] Base window class

_Everything above is preparation to do what's below. I'm fairly confident that there will not be any need for other people to test the stuff above but it wouldn't hurt_. **Will mostly likely require help testing changes to the modeless dialogs however**.

## Modal Dialogs
- [ ] Login 
- [ ] Checksum 
- [ ] Game title
- [ ] Achievement reporter

## Modeless Dialogs
- [ ] RichPresence dialog
- [ ] Game library dialog
- [ ] Achievement 
- [ ] Achievement editor 
- [ ] MemoryViewControl
- [ ] Memory Dialog
- [ ] Achievement set dialog
- [ ] Memory bookmark dialog

## Controls
- [ ] Custom controls will be in their own classes or subclassed from a dialog (one example is ProcessCustomDraw in the Achievement Dialog)

**Comment by meleu** [comment]
hey @SyrianBallaS , sorry for bothering you again. :sweat_smile: 

But I realized that the cleanest way to separate `RA_Integration` code from the rest of the files of this repo is creating a new dedicated repo for it. And I did: https://github.com/RetroAchievements/RAIntegration

I used some git tricks to keep the commit history only of RA_Integration's file (thanks to @Jamiras for showing me some docs about git).

I've moved all opened issues from this issue tracker here to that new repo's one. But I think that in your case it would be better if you open an issue by yourself, because looks like you want to edit the OP from time to time.

Would you mind to open this very same issue on that repo?

Cheers!

**Comment by SyrianBallaS** [comment]
It's done.

**Comment by meleu** [comment]
Just for register:

This issue was moved to RetroAchievements/RAIntegration#19
